/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import clases.Usuario;
import static forms.crearGasto.getArrayFromJson;
import static forms.crearGasto.getJSONString;
import static forms.crearGasto.getObj;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author ezequ
 */
public class actualizarSaldo extends javax.swing.JFrame {

    String username = "";

    /**
     * Creates new form actualizarSaldo
     */
    public actualizarSaldo(String user) {
        try {
            initComponents();
            username = user;
            JSONParser parser = new JSONParser();
            Object obj = parser.parse(new FileReader(".\\src\\forms\\dataSrc/" + username + ".json"));
            org.json.simple.JSONObject jsonObjectA = (org.json.simple.JSONObject) obj;
            long saldo = (long) jsonObjectA.get("saldo");
            lblSaldo.setText("Su saldo actual es de $" + (saldo - obtenerMontoTotal(username)));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSaldoPAgregar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarSaldo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblNuevoSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actualizar Saldo");

        lblSaldo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("Su saldo actual es de ");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setText("Desea añadir");

        txtSaldoPAgregar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("$");

        btnAgregarSaldo.setBackground(new java.awt.Color(16, 125, 216));
        btnAgregarSaldo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnAgregarSaldo.setForeground(new java.awt.Color(250, 250, 250));
        btnAgregarSaldo.setText("Agregar saldo");
        btnAgregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSaldoActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(16, 125, 216));
        btnVolver.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(250, 250, 250));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblNuevoSaldo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblNuevoSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNuevoSaldo.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoPAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNuevoSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSaldo)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldoPAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblNuevoSaldo)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSaldoActionPerformed
        agregarSaldo(txtSaldoPAgregar.getText(), username);
    }//GEN-LAST:event_btnAgregarSaldoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        main volver = new main(username);
        volver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarSaldo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNuevoSaldo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtSaldoPAgregar;
    // End of variables declaration//GEN-END:variables

    public static float obtenerMontoTotal(String user) {
        float montoTotal = 0;
        try {
            JSONObject jsonObj = new JSONObject(getJSONString(".\\src\\forms\\dataSrc/" + user + ".json"));
            JSONArray result = jsonObj.getJSONArray("gastos");
            for (int i = 0; i < result.length(); i++) {
                JSONObject jsonObject = result.getJSONObject(i);
                montoTotal += (float) jsonObject.getFloat("monto");
            }
            return montoTotal;
        } catch (Exception e) {
            System.out.println(e);
            return -1;
        }
    }

    public void agregarSaldo(String saldoPAgregar, String user) {
        try {
            float saldoAgregar = Float.parseFloat(saldoPAgregar);
            String jsonData = getJSONString(".\\src\\forms\\dataSrc/" + user + ".json");
            ArrayList gastos = getArrayFromJson(jsonData);
            Usuario usuario = getObj(user, gastos);
            float saldoAntiguo = usuario.getSaldo();
            usuario.setSaldo(saldoAntiguo + saldoAgregar);
            writeJson(usuario, gastos);
            lblNuevoSaldo.setText("El nuevo saldo es $" + (usuario.getSaldo() - obtenerMontoTotal(user)));

        } catch (Exception e) {
            System.out.println(e);
            lblNuevoSaldo.setText("No se ha podido actualizar el saldo");
        }
    }

    public static void writeJson(Usuario user, ArrayList gastos) {
        String path = ".\\src\\forms\\dataSrc/" + user.getNombre() + ".json";
        JSONObject jsonObj = new JSONObject();
        try {
            jsonObj.put("usuario", user.getNombre());
            jsonObj.put("edad", user.getEdad());
            jsonObj.put("celular", user.getCelular());
            jsonObj.put("saldo", user.getSaldo());
            jsonObj.put("gastos", gastos);
            jsonObj.put("contrasenia", user.getContrasenia());
        } catch (JSONException e) {
            e.printStackTrace();
        }

        try ( PrintWriter out = new PrintWriter(new FileWriter(path))) {
            out.write(jsonObj.toString());

        } catch (Exception e) {
            System.out.println(e);
        }

    }
}
