/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author ezequ
 */
public class main extends javax.swing.JFrame {

    String userMain = "";

    /**
     * Creates new form main
     */
    public main(String user) {
        initComponents();

        userMain = user;
        lblCond.setText("Bienvenido " + user + "!");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCargarGasto = new javax.swing.JButton();
        btnUltimosGastos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnActualizarSaldo = new javax.swing.JButton();
        lblCond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(179, 228, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setText("Recuento de Gastos");

        btnCargarGasto.setBackground(new java.awt.Color(16, 125, 216));
        btnCargarGasto.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnCargarGasto.setForeground(new java.awt.Color(250, 250, 250));
        btnCargarGasto.setText("Cargar gasto");
        btnCargarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarGastoActionPerformed(evt);
            }
        });

        btnUltimosGastos.setBackground(new java.awt.Color(16, 125, 216));
        btnUltimosGastos.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnUltimosGastos.setForeground(new java.awt.Color(250, 250, 250));
        btnUltimosGastos.setText("Ultimos gastos");
        btnUltimosGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimosGastosActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(16, 125, 216));
        btnSalir.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(250, 250, 250));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Source Sans Pro Light", 1, 12)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText(" ");
        lblWelcome.setToolTipText("");

        btnActualizarSaldo.setBackground(new java.awt.Color(16, 125, 216));
        btnActualizarSaldo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        btnActualizarSaldo.setForeground(new java.awt.Color(250, 250, 250));
        btnActualizarSaldo.setText("Actualizar saldo");
        btnActualizarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSaldoActionPerformed(evt);
            }
        });

        lblCond.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblCond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCond.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCargarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnActualizarSaldo)
                        .addGap(32, 32, 32)
                        .addComponent(btnUltimosGastos))
                    .addComponent(lblCond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblWelcome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGap(4, 4, 4)
                .addComponent(lblCond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUltimosGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCargarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarGastoActionPerformed
        crearGasto ventana = new crearGasto(userMain);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCargarGastoActionPerformed

    private void btnUltimosGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimosGastosActionPerformed
        muestraGatos ventanaMuestra = new muestraGatos((userMain));
        ventanaMuestra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUltimosGastosActionPerformed

    private void btnActualizarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSaldoActionPerformed
        actualizarSaldo ventana = new actualizarSaldo(userMain);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActualizarSaldoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarSaldo;
    private javax.swing.JButton btnCargarGasto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUltimosGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCond;
    public javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables

}
